[package]
name = "tunnet-extended-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
dll-syringe = "0.15.2"

[dependencies.windows]
version = "0.*"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
]